version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app-logs:/mnt/app-logs
    environment:
      - NODE_ENV=production